// GVCN Penal Code data
// classification: "felony" | "misdemeanor" | "citation" | "eviction"
// jail: seconds | fine: dollars | impound: bool

const TITLES = [
  "Title 1: Crimes Against People",
  "Title 2: Crimes Against Property",
  "Title 3: Crimes Against Public Decency",
  "Title 4: Crimes Against Criminal Justice",
  "Title 5: Crimes Against Public Peace",
  "Title 6: Traffic Offenses",
  "Title 7: Control of a Deadly Weapon and Equipment",
  "Title 8: Crimes Against Nature",
];

// One accent color per Title, used to color-code search results & the list
const TITLE_COLORS = [
  "rgb(255, 0, 0)", // Title 1 — People
  "#ff9d00", // Title 2 — Property
  "#8000ff", // Title 3 — Public Decency
  "#00e5ff", // Title 4 — Criminal Justice
  "#00ff08", // Title 5 — Public Peace
  "#1500ff", // Title 6 — Traffic
  "#ff00b3", // Title 7 — Weapons
  "#a0663a", // Title 8 — Nature
];

const CHARGES = [
  // Title 1: Crimes Against People
  { code: "1-01", title: 0, name: "Criminal Threats", cls: "misdemeanor", jail: 30, fine: 700 },
  { code: "1-02", title: 0, name: "Assault with a Deadly Weapon", cls: "felony", jail: 120, fine: 1500 },
  { code: "1-03", title: 0, name: "Battery", cls: "misdemeanor", jail: 60, fine: 1000 },
  { code: "1-04", title: 0, name: "Aggravated Battery", cls: "felony", jail: 120, fine: 1000 },
  { code: "1-05", title: 0, name: "Attempted Murder", cls: "felony", jail: 90, fine: 9000 },
  { code: "1-06", title: 0, name: "Manslaughter", cls: "felony", jail: 150, fine: 2000 },
  { code: "1-07", title: 0, name: "Murder", cls: "felony", jail: 120, fine: 2500 },
  { code: "1-08", title: 0, name: "False Imprisonment", cls: "misdemeanor", jail: 60, fine: 1000 },
  { code: "1-09", title: 0, name: "Kidnapping", cls: "felony", jail: 150, fine: 6500 },
  { code: "1-10", title: 0, name: "Homicide", cls: "felony", jail: 120, fine: 5000 },
  { code: "1-11", title: 0, name: "False Imprisonment", cls: "felony", jail: 120, fine: 1500 },
  { code: "1-12", title: 0, name: "Assault on a Public Servant", cls: "felony", jail: 120, fine: 1000 },
  { code: "1-13", title: 0, name: "Attempted Assault on a Public Servant", cls: "felony", jail: 100, fine: 1000 },
  { code: "1-14", title: 0, name: "Attempted Assault", cls: "felony", jail: 100, fine: 1000 },
  { code: "1-15", title: 0, name: "Assault on a Peace Officer", cls: "felony", jail: 180, fine: 2000 },

  // Title 2: Crimes Against Property
  { code: "2-01", title: 1, name: "Arson", cls: "felony", jail: 230, fine: 5000 },
  { code: "2-02", title: 1, name: "Trespassing", cls: "misdemeanor", jail: 30, fine: 1000 },
  { code: "2-03", title: 1, name: "Trespassing within a Restricted Facility", cls: "felony", jail: 60, fine: 1000 },
  { code: "2-04", title: 1, name: "Burglary", cls: "felony", jail: 150, fine: 250 },
  { code: "2-05", title: 1, name: "Possession of Burglary Tools", cls: "misdemeanor", jail: 30, fine: 1000 },
  { code: "2-06", title: 1, name: "Robbery", cls: "felony", jail: 120, fine: 6000 },
  { code: "2-07", title: 1, name: "Armed Robbery", cls: "felony", jail: 150, fine: 7500 },
  { code: "2-08", title: 1, name: "Petty Theft", cls: "misdemeanor", jail: 0, fine: 1000 },
  { code: "2-09", title: 1, name: "Grand Theft", cls: "felony", jail: 90, fine: 800 },
  { code: "2-10", title: 1, name: "Grand Theft Auto", cls: "felony", jail: 160, fine: 6000 },
  { code: "2-11", title: 1, name: "Receiving Stolen Property", cls: "felony", jail: 90, fine: 10000 },
  { code: "2-12", title: 1, name: "Extortion", cls: "felony", jail: 150, fine: 10000 },
  { code: "2-13", title: 1, name: "Forgery/Fraud", cls: "felony", jail: 90, fine: 250 },
  { code: "2-14", title: 1, name: "Vandalism", cls: "misdemeanor", jail: 30, fine: 750 },
  { code: "2-15", title: 1, name: "Loitering", cls: "misdemeanor", jail: 30, fine: 1000 },
  { code: "2-16", title: 1, name: "Destruction of Civilian Property", cls: "misdemeanor", jail: 120, fine: 1000 },
  { code: "2-17", title: 1, name: "Destruction of Government Property", cls: "felony", jail: 230, fine: 10000 },
  { code: "2-18", title: 1, name: "Criminal Mischief", cls: "misdemeanor", jail: 30, fine: 750 },
  { code: "2-19", title: 1, name: "Possession of a Stolen Vehicle", cls: "felony", jail: 90, fine: 5000 },
  { code: "2-20", title: 1, name: "Attempted Burglary", cls: "felony", jail: 120, fine: 4000 },
  { code: "2-21", title: 1, name: "Shoplifting", cls: "misdemeanor", jail: 30, fine: 500 },
  { code: "2-22", title: 1, name: "Criminal Tampering", cls: "misdemeanor", jail: 30, fine: 750 },
  { code: "2-23", title: 1, name: "Insurance Fraud", cls: "felony", jail: 60, fine: 2000 },

  // Title 3: Crimes Against Public Decency
  { code: "3-01", title: 2, name: "Lewd or Dissolute Conduct In Public", cls: "misdemeanor", jail: 90, fine: 500 },
  { code: "3-02", title: 2, name: "Stalking", cls: "misdemeanor", jail: 90, fine: 500 },

  // Title 4: Crimes Against Criminal Justice
  { code: "4-01", title: 3, name: "Bribery", cls: "felony", jail: 120, fine: 10000 },
  { code: "4-02", title: 3, name: "Dissuading a Victim", cls: "felony", jail: 60, fine: 500 },
  { code: "4-03", title: 3, name: "False Information to a Peace Officer", cls: "misdemeanor", jail: 120, fine: 500 },
  { code: "4-04", title: 3, name: "Filing a False Police Report", cls: "misdemeanor", jail: 60, fine: 500 },
  { code: "4-05", title: 3, name: "Failure to Identify to a Peace Officer", cls: "misdemeanor", jail: 60, fine: 1000 },
  { code: "4-06", title: 3, name: "Impersonation of a Public Employees", cls: "misdemeanor", jail: 60, fine: 1000 },
  { code: "4-07", title: 3, name: "Obstruction of a Peace Officer", cls: "misdemeanor", jail: 60, fine: 1000 },
  { code: "4-08", title: 3, name: "Resisting a Peace Officer", cls: "misdemeanor", jail: 120, fine: 1000 },
  { code: "4-09", title: 3, name: "Escape from Custody", cls: "felony", jail: 210, fine: 1000 },
  { code: "4-10", title: 3, name: "Prisoner Breakout", cls: "felony", jail: 90, fine: 10000 },
  { code: "4-11", title: 3, name: "Misuse of Government Hotline", cls: "misdemeanor", jail: 0, fine: 1000 },
  { code: "4-12", title: 3, name: "Tampering with Evidence", cls: "misdemeanor", jail: 0, fine: 1000 },
  { code: "4-13", title: 3, name: "Introduction of Contraband", cls: "felony", jail: 120, fine: 250 },
  { code: "4-14", title: 3, name: "False Arrest", cls: "felony", jail: 120, fine: 10000 },
  { code: "4-15", title: 3, name: "Failure to Inform", cls: "misdemeanor", jail: 0, fine: 500 },
  { code: "4-16", title: 3, name: "Obstruction of Justice", cls: "felony", jail: 30, fine: 500 },
  { code: "4-17", title: 3, name: "Disorderly Conduct", cls: "misdemeanor", jail: 60, fine: 1000 },
  { code: "4-18", title: 3, name: "Failure to Comply with a Lawful Order", cls: "misdemeanor", jail: 30, fine: 500 },
  { code: "4-19", title: 3, name: "Aiding and Abetting", cls: "misdemeanor", jail: 90, fine: 250 },
  { code: "4-20", title: 3, name: "Perjury", cls: "felony", jail: 90, fine: 2500 },
  { code: "4-21", title: 3, name: "Contempt of Court", cls: "misdemeanor", jail: 60, fine: 1000 },
  { code: "4-22", title: 3, name: "Escape from Custody (Attempted)", cls: "felony", jail: 120, fine: 5000 },
  { code: "4-23", title: 3, name: "Unpaid Citation(s)", cls: "misdemeanor", jail: 60, fine: 400 },
  { code: "4-24", title: 3, name: "Harboring a Fugitive", cls: "felony", jail: 120, fine: 2000 },
  { code: "4-25", title: 3, name: "Fleeing an Incident", cls: "misdemeanor", jail: 60, fine: 700 },
  { code: "4-26", title: 3, name: "False Alarm", cls: "misdemeanor", jail: 60, fine: 300 },
  { code: "4-27", title: 3, name: "Possession of a Fraudulent ID", cls: "misdemeanor", jail: 30, fine: 900 },
  { code: "4-28", title: 3, name: "Possession of a Fraudulent Insurance", cls: "citation", jail: 0, fine: 1000 },

  // Title 5: Crimes Against Public Peace
  { code: "5-01", title: 4, name: "Disturbing the Peace", cls: "misdemeanor", jail: 0, fine: 500 },
  { code: "5-02", title: 4, name: "Unlawful Assembly", cls: "felony", jail: 90, fine: 0 },
  { code: "5-03", title: 4, name: "Inciting Riot", cls: "felony", jail: 120, fine: 1000 },
  { code: "5-04", title: 4, name: "Distribution of Food(s) w/o Proper Documents", cls: "misdemeanor", jail: 0, fine: 900 },

  // Title 6: Traffic Offenses
  { code: "6-01", title: 5, name: "Invalid/No Vehicle Registration/Insurance", cls: "citation", jail: 0, fine: 200, impound: true },
  { code: "6-02", title: 5, name: "Driving Without a License", cls: "citation", jail: 0, fine: 1000, impound: true },
  { code: "6-03", title: 5, name: "Driving With a Suspended or Revoked License", cls: "misdemeanor", jail: 60, fine: 1000, impound: true },
  { code: "6-04", title: 5, name: "Accident Reporting Requirements – Property Damage", cls: "misdemeanor", jail: 0, fine: 1000, impound: true },
  { code: "6-05", title: 5, name: "Accident Reporting Requirements – Injury or Death", cls: "felony", jail: 120, fine: 10000 },
  { code: "6-06", title: 5, name: "Failure to Obey Traffic Signal", cls: "citation", jail: 0, fine: 250 },
  { code: "6-07", title: 5, name: "Driving Opposite Lanes", cls: "misdemeanor", jail: 0, fine: 500 },
  { code: "6-08", title: 5, name: "Failure to Maintain Lane", cls: "citation", jail: 0, fine: 250 },
  { code: "6-09", title: 5, name: "Unsafe Following Distance", cls: "citation", jail: 0, fine: 250 },
  { code: "6-10", title: 5, name: "Failure to Yield to Civilian", cls: "citation", jail: 0, fine: 250 },
  { code: "6-11", title: 5, name: "Failure to Yield to Emergency Vehicle", cls: "citation", jail: 0, fine: 500 },
  { code: "6-12", title: 5, name: "Unsafe Turn", cls: "citation", jail: 0, fine: 250 },
  { code: "6-13", title: 5, name: "Unsafe Lane Change", cls: "citation", jail: 0, fine: 250 },
  { code: "6-14", title: 5, name: "Illegal U-Turn", cls: "citation", jail: 0, fine: 250 },
  { code: "6-15", title: 5, name: "Speeding (5-15 MPH Over)", cls: "citation", jail: 0, fine: 250 },
  { code: "6-16", title: 5, name: "Speeding (16-30 MPH Over)", cls: "citation", jail: 0, fine: 360 },
  { code: "6-17", title: 5, name: "Felony Speeding (31+ MPH Over)", cls: "felony", jail: 80, fine: 880 },
  { code: "6-18", title: 5, name: "Unreasonably Slow / Stopped", cls: "citation", jail: 0, fine: 250 },
  { code: "6-19", title: 5, name: "Failure to Obey Stop Sign", cls: "citation", jail: 0, fine: 250 },
  { code: "6-20", title: 5, name: "Illegally Parked", cls: "citation", jail: 0, fine: 250, impound: true },
  { code: "6-21", title: 5, name: "Reckless Driving", cls: "misdemeanor", jail: 60, fine: 1000 },
  { code: "6-22", title: 5, name: "Street Racing", cls: "misdemeanor", jail: 0, fine: 400, impound: true },
  { code: "6-23", title: 5, name: "Throwing Objects", cls: "misdemeanor", jail: 0, fine: 1000 },
  { code: "6-24", title: 5, name: "Operating While Intoxicated", cls: "misdemeanor", jail: 60, fine: 2000, impound: true },
  { code: "6-25", title: 5, name: "Enhanced Operating While Intoxicated", cls: "felony", jail: 120, fine: 4000, impound: true },
  { code: "6-26", title: 5, name: "Alcohol Beverages in Motor Vehicles", cls: "citation", jail: 0, fine: 400 },
  { code: "6-27", title: 5, name: "Evading a Peace Officer", cls: "misdemeanor", jail: 270, fine: 250 },
  { code: "6-28", title: 5, name: "Felony Evading a Peace Officer", cls: "felony", jail: 350, fine: 250 },
  { code: "6-29", title: 5, name: "Road Rage", cls: "misdemeanor", jail: 0, fine: 1500 },
  { code: "6-30", title: 5, name: "Littering", cls: "citation", jail: 0, fine: 1000 },
  { code: "6-31", title: 5, name: "Unsafe Speed for Conditions", cls: "citation", jail: 0, fine: 2000 },
  { code: "6-32", title: 5, name: "Public Endangerment", cls: "misdemeanor", jail: 0, fine: 1000 },
  { code: "6-33", title: 5, name: "Impeding Traffic", cls: "citation", jail: 0, fine: 250 },
  { code: "6-34", title: 5, name: "Jaywalking", cls: "citation", jail: 0, fine: 250 },
  { code: "6-35", title: 5, name: "Unnecessary Use of Horn", cls: "citation", jail: 0, fine: 480 },
  { code: "6-36", title: 5, name: "Excessive Vehicle Sounds", cls: "citation", jail: 0, fine: 400 },
  { code: "6-37", title: 5, name: "Failure to Sign Citation", cls: "misdemeanor", jail: 30, fine: 250, impound: true },
  { code: "6-38", title: 5, name: "Failure to Yield to Pedestrian", cls: "citation", jail: 0, fine: 250 },
  { code: "6-39", title: 5, name: "Distracted Driving", cls: "citation", jail: 0, fine: 1000 },
  { code: "6-40", title: 5, name: "Driving on Shoulder/Emergency Lane", cls: "citation", jail: 0, fine: 250 },
  { code: "6-41", title: 5, name: "Failure to Yield for Emergency Services", cls: "citation", jail: 0, fine: 1000 },
  { code: "6-42", title: 5, name: "Driving Without Headlights", cls: "citation", jail: 0, fine: 250 },
  { code: "6-43", title: 5, name: "Hit and Run", cls: "misdemeanor", jail: 0, fine: 500, impound: true },
  { code: "6-44", title: 5, name: "Attempted Vehicular Manslaughter", cls: "felony", jail: 60, fine: 750 },
  { code: "6-45", title: 5, name: "Vehicular Manslaughter", cls: "felony", jail: 120, fine: 750 },
  { code: "6-46", title: 5, name: "Reckless Evasion", cls: "felony", jail: 120, fine: 750 },
  { code: "6-47", title: 5, name: "Possession of a Stolen Vehicle", cls: "felony", jail: 120, fine: 750 },
  { code: "6-48", title: 5, name: "Reckless Endangerment", cls: "misdemeanor", jail: 60, fine: 1000 },
  { code: "6-49", title: 5, name: "Unroadworthy Vehicle", cls: "misdemeanor", jail: 0, fine: 1000, impound: true },
  { code: "6-50", title: 5, name: "Passing a Stopped School Bus", cls: "misdemeanor", jail: 0, fine: 1000 },
  { code: "6-51", title: 5, name: "Speeding in a School Zone (5+ MPH Over)", cls: "misdemeanor", jail: 0, fine: 1000 },
  { code: "6-52", title: 5, name: "Drifting", cls: "misdemeanor", jail: 60, fine: 1000, impound: true },
  { code: "6-53", title: 5, name: "Exhibition of Speed", cls: "misdemeanor", jail: 45, fine: 750, impound: true },
  { code: "6-54", title: 5, name: "Burnout", cls: "citation", jail: 0, fine: 400 },
  { code: "6-55", title: 5, name: "Failure to Maintain Control of Vehicle", cls: "citation", jail: 0, fine: 350 },
  { code: "6-56", title: 5, name: "Unsafe Passing", cls: "citation", jail: 0, fine: 250 },
  { code: "6-57", title: 5, name: "Passing in No Passing Zone", cls: "citation", jail: 0, fine: 300 },
  { code: "6-58", title: 5, name: "Following Emergency Vehicle Too Closely", cls: "citation", jail: 0, fine: 400 },
  { code: "6-59", title: 5, name: "Failure to Move Over for Emergency Vehicle", cls: "citation", jail: 0, fine: 500 },
  { code: "6-60", title: 5, name: "Obstruction of Traffic", cls: "citation", jail: 0, fine: 350 },
  { code: "6-61", title: 5, name: "Blocking Intersection", cls: "citation", jail: 0, fine: 300 },
  { code: "6-62", title: 5, name: "Improper Turn", cls: "citation", jail: 0, fine: 250 },
  { code: "6-63", title: 5, name: "Driving Without Due Regard", cls: "citation", jail: 0, fine: 400 },
  { code: "6-64", title: 5, name: "Operating Unsafe Vehicle", cls: "citation", jail: 0, fine: 500 },
  { code: "6-65", title: 5, name: "Improper Display of License Plate", cls: "citation", jail: 0, fine: 250 },
  { code: "6-67", title: 5, name: "Illegal Window Tint", cls: "citation", jail: 0, fine: 250 },
  { code: "6-68", title: 5, name: "Illegal Vehicle Modifications", cls: "citation", jail: 0, fine: 500 },
  { code: "6-69", title: 5, name: "Driving on a Sidewalk", cls: "citation", jail: 0, fine: 400 },
  { code: "6-70", title: 5, name: "Endangering Pedestrians", cls: "misdemeanor", jail: 60, fine: 1000 },
  { code: "6-71", title: 5, name: "Unsafe Reversing", cls: "citation", jail: 0, fine: 250 },
  { code: "6-72", title: 5, name: "Going Around the Crossing Gates", cls: "citation", jail: 0, fine: 360 },
  { code: "6-73", title: 5, name: "Driving the Wrong Way on a One-Way Road", cls: "citation", jail: 0, fine: 400 },
  { code: "6-74", title: 5, name: "Unsafe Lane Merge", cls: "citation", jail: 0, fine: 350 },
  { code: "6-75", title: 5, name: "Failure to Dim Headlights", cls: "citation", jail: 0, fine: 250 },
  { code: "6-76", title: 5, name: "Improper Use of High Beams", cls: "citation", jail: 0, fine: 250 },
  { code: "6-77", title: 5, name: "Following Too Closely to an Emergency Vehicle", cls: "citation", jail: 0, fine: 500 },
  { code: "6-78", title: 5, name: "Failure to Obey Traffic Control Device", cls: "citation", jail: 0, fine: 300 },
  { code: "6-79", title: 5, name: "Failure to Obey Railroad Crossing Signals", cls: "citation", jail: 0, fine: 500 },
  { code: "6-80", title: 5, name: "Unsafe Backing", cls: "citation", jail: 0, fine: 300 },
  { code: "6-81", title: 5, name: "Crossing a Median", cls: "citation", jail: 0, fine: 400 },
  { code: "6-82", title: 5, name: "Failure to Secure Vehicle (Left Unattended)", cls: "citation", jail: 0, fine: 250 },
  { code: "6-83", title: 5, name: "Improper Use of Turn Lane", cls: "citation", jail: 0, fine: 250 },
  { code: "6-84", title: 5, name: "Unsafe Passing of a School Bus", cls: "misdemeanor", jail: 60, fine: 1000 },
  { code: "6-85", title: 5, name: "Failure to Stop at a Railroad Crossing (Commercial Vehicle)", cls: "misdemeanor", jail: 60, fine: 1000 },
  { code: "6-86", title: 5, name: "Driving Without Required Safety Equipment", cls: "citation", jail: 0, fine: 400 },
  { code: "6-87", title: 5, name: "Improper Towing of a Vehicle", cls: "citation", jail: 0, fine: 500 },
  { code: "6-88", title: 5, name: "Operating a Vehicle with an Obstructed View", cls: "citation", jail: 0, fine: 350 },
  { code: "6-89", title: 5, name: "Improper Load Securement", cls: "citation", jail: 0, fine: 500 },
  { code: "6-90", title: 5, name: "Failure to Abide by Curfew", cls: "citation", jail: 0, fine: 250 },
  { code: "6-91", title: 5, name: "Vehicular Assault", cls: "citation", jail: 60, fine: 2000 },
  { code: "6-92", title: 5, name: "At Fault at an Injury", cls: "citation", jail: 60, fine: 1500 },
  { code: "6-93", title: 5, name: "Causing a Crash", cls: "citation", jail: 0, fine: 2000 },
  { code: "6-94", title: 5, name: "Causing Crash with Death", cls: "citation", jail: 120, fine: 1500 },
  { code: "6-95", title: 5, name: "Hands Free Violation", cls: "citation", jail: 0, fine: 400 },
  { code: "6-96", title: 5, name: "Curb Hopping", cls: "citation", jail: 0, fine: 500 },
  { code: "6-97", title: 5, name: "Failure to Properly Attach Front Plate", cls: "citation", jail: 0, fine: 400 },
  { code: "6-98", title: 5, name: "Failure to Safely Operate Self Driven Vehicle", cls: "citation", jail: 0, fine: 500 },
  { code: "6-99", title: 5, name: "Improper Usage of Warning Lights", cls: "citation", jail: 0, fine: 100 },

  // Title 7: Control of a Deadly Weapon and Equipment
  { code: "7-01", title: 6, name: "Possession of an Illegal Weapon", cls: "misdemeanor", jail: 60, fine: 1000 },
  { code: "7-02", title: 6, name: "Brandishing a Firearm", cls: "misdemeanor", jail: 60, fine: 1000 },
  { code: "7-03", title: 6, name: "Illegal Discharge of a Firearm", cls: "felony", jail: 90, fine: 500 },
  { code: "7-04", title: 6, name: "Unlicensed Possession of a Firearm", cls: "felony", jail: 90, fine: 500 },
  { code: "7-05", title: 6, name: "Possession of a Stolen Weapon", cls: "felony", jail: 90, fine: 500 },
  { code: "7-06", title: 6, name: "Unlawful Distribution of a Firearm", cls: "felony", jail: 90, fine: 500 },
  { code: "7-07", title: 6, name: "Possession of a Firearm by a Convicted Felon", cls: "felony", jail: 120, fine: 5000 },
  { code: "7-08", title: 6, name: "Possession of a Firearm During the Commission of a Crime", cls: "felony", jail: 120, fine: 5000 },
  { code: "7-09", title: 6, name: "Unlawful Transfer of a Firearm", cls: "felony", jail: 90, fine: 2500 },
  { code: "7-10", title: 6, name: "Tampering with a Firearm Serial Number", cls: "felony", jail: 120, fine: 5000 },
  { code: "7-11", title: 6, name: "Possession of a Firearm with an Obliterated Serial Number", cls: "felony", jail: 90, fine: 3000 },
  { code: "7-12", title: 6, name: "Possession of a Prohibited Weapon", cls: "felony", jail: 90, fine: 3000 },
  { code: "7-13", title: 6, name: "Unlawful Sale of a Firearm", cls: "felony", jail: 120, fine: 5000 },
  { code: "7-14", title: 6, name: "Negligent Storage of a Firearm", cls: "misdemeanor", jail: 30, fine: 1000 },
  { code: "7-15", title: 6, name: "Reckless Handling of a Firearm", cls: "misdemeanor", jail: 60, fine: 1500 },
  { code: "7-16", title: 6, name: "Possession of a Firearm in a Restricted Area", cls: "misdemeanor", jail: 60, fine: 1000 },

  // Title 8: Crimes Against Nature
  { code: "8-01", title: 7, name: "Unlawfully Injuring Wildlife", cls: "misdemeanor", jail: 0, fine: 1000 },
  { code: "8-02", title: 7, name: "Unlawful Sale of Wildlife", cls: "misdemeanor", jail: 90, fine: 2000 },
  { code: "8-03", title: 7, name: "Unlawfully Harvesting Natural Resources", cls: "misdemeanor", jail: 30, fine: 600 },
  { code: "8-04", title: 7, name: "Unlawful Captivity of Wildlife", cls: "misdemeanor", jail: 30, fine: 900 },
  { code: "8-05", title: 7, name: "Disruption of Wildlife", cls: "citation", jail: 0, fine: 500 },
  { code: "8-06", title: 7, name: "Camping on a Non-designated Campground", cls: "citation", jail: 0, fine: 150 },
  { code: "8-07", title: 7, name: "In Park After Hours", cls: "citation", jail: 0, fine: 150 },
  { code: "8-08", title: 7, name: "Trespassing on Rail Road Property", cls: "misdemeanor", jail: 30, fine: 800 },
  { code: "8-09", title: 7, name: "Illegally Harvesting Game (per animal)", cls: "misdemeanor", jail: 60, fine: 2000 },
  { code: "8-10", title: 7, name: "Possession of Illegally Harvested Game (per animal)", cls: "misdemeanor", jail: 30, fine: 800 },
  { code: "8-11", title: 7, name: "Destroying Wildlife By Means Of Arson", cls: "felony", jail: 180, fine: 15000 },
  { code: "8-12", title: 7, name: "Illegal Off-Roading", cls: "citation", jail: 0, fine: 250 },
  { code: "8-13", title: 7, name: "Trespassing on a National Park", cls: "misdemeanor", jail: 0, fine: 150 },
  { code: "8-14", title: 7, name: "Camping Without a Permit", cls: "eviction", jail: 0, fine: 0 },
  { code: "8-15", title: 7, name: "Discharge of Firearm Within a National Park", cls: "felony", jail: 100, fine: 8000 },
  { code: "8-16", title: 7, name: "Littering Within a National Park", cls: "citation", jail: 0, fine: 150 },
  { code: "8-17", title: 7, name: "Entering a Restricted Area of a National Park", cls: "misdemeanor", jail: 90, fine: 800 },
];